### ISSUE TITLE
Add ReadM (and related) for other types

### ISSUE THREAD

**Issue by adelbertc** [bmjames/scala-optparse-applicative#4]
e.g. Short, Long, BigInt

Should these be placed in the same place as the [existing ones](https://github.com/bmjames/scala-optparse-applicative/blob/f0523021398885761b0b96a9be6afb1382c12f1c/src/main/scala/net/bmjames/opts/builder/Builder.scala) or in a separate place?

**Comment by adelbertc** [comment]
https://github.com/bmjames/scala-optparse-applicative/pull/5

**Comment by bmjames** [comment]
#5 is now merged, thanks.
